[Icon Theme]
Name=OieIcons
Comment=Lines of icons for fun (;P)

Inherits=breeze,Papirus,gnome,Numix-Circle

Example=directory-x-normal

FollowsColorScheme=true


# Directory list
Directories=scalable/apps,scalable/mimetypes,devices

[scalable/apps]
Size=48
Context=Applications
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Size=22
Context=MimeTypes
MinSize=22
MaxSize=512
Type=Scalable

[devices]
Size=48
Context=Devices
Type=Scalable
MinSize=16
MaxSize=96
